### ISSUE TITLE
Error on every HA start: 'DeviceTools' object has no attribute '_device_modifications'

### ISSUE THREAD

**Issue by MrEbbinghaus** [EuleMitKeule/device-tools#11]
Hey, 

I get this error every time HomeAssistant starts:
```
Traceback (most recent call last):
  File "/config/custom_components/device_tools/device_tools.py", line 84, in async_run
    self.async_get_entries()
  File "/config/custom_components/device_tools/device_tools.py", line 72, in async_get_entries
    if self._device_modifications == device_modifications:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DeviceTools' object has no attribute '_device_modifications'
```

**Comment by EuleMitKeule** [comment]
I can't replicate this on the newest version. Did you check HACS if there are any available updates for this integration?

**Comment by MrEbbinghaus** [comment]
I updated from 1.8.2 to 1.8.3 and the message is gone.
